### ISSUE TITLE
In mobile qpdfviewer displays only the first page without scrolling

### ISSUE THREAD

**Issue by jhoonb** [quasarframework/app-extension-qpdfviewer#115]
I tested the application in the browser it works perfectly, but on mobile (iphone 7: Chrome and Safari) it only displays the first page of the PDF, I can't scroll the content and access the other pages.

Is this behavior correct? How do I display the entire content on mobile?

configs:

quasar: ^2.6.2,
vuex: ^4.0.2

node: >= 12.22.1,
npm: >= 6.13.4,

@quasar/app-webpack: ^3.4.6,
@quasar/quasar-app-extension-qpdfviewer: ^2.0.0-alpha.5

**Comment by hawkeye64** [comment]
Are you using native HTML5 PDF viewer or the PDFjs one? Whatever one you are using, try the other one and let me know how it goes.

**Comment by jhoonb** [comment]
I use HTML5 but I tried with PDFjs too.

**Comment by hawkeye64** [comment]
Tested with iPhone 7 Safari and can confirm that HTML5 will only show the first page. PDFjs does not work at all. Chrome also exhibited the same, but not surprised, since all other web browsers on iOS are a wrapper around Safari

Tested with iPhone 8 Safari. Still only 1st page for HTML5 rendering, but PDFjs now works, with multiple pages too.

Tested with latest iPhone 13. Same as iPhone 8.

Tested with iPad 9th. Same as iPhone 8.

The issue here is that Safari is not drawing the embedded HTML5 Pdf Viewer's toolbar, which is where you would change pages. For iPhone 7, PDFjs is broken, but works for iPhone 8 and up.

Sorry, not much else that can be done for iPhone 7.

**Comment by MartinX3** [comment]
It's broken since iOS 8
https://forums.developer.apple.com/forums/thread/649982

Apple needs to fix it.
