### ISSUE TITLE
is it correct that PDFjs is added inside statics?

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/app-extension-qpdfviewer#31]
is it correct that PDFjs is added inside statics?
it's 10 MB large. ( ﾟ▽ ﾟ*)

**Comment by yusufkandemir** [comment]
@mesqueeb yes it gets [added ](https://github.com/quasarframework/app-extension-qpdfviewer/blob/fd10c8ade794dd4799d267cbdc04c5e29f0b0f40/src/install.js#L2) into `statics` folder when this app-ext gets installed. It has multiple images, locales, source maps and CMaps so it is quite big. But don't worry not all of it gets used in the production, they are dynamically loaded.

There are some plans to build a PDF viewer using PDF.js but with Quasar components, that way it will look more coherent with the whole application and be much lighter since we will make use of existing components(instead of lots of HTML, CSS, and JS in the current viewer) and icon sets(instead of png icons in the current viewer), but no release date or promises.

**Comment by mesqueeb** [comment]
@yusufkandemir I understand! Thanks for the insight ;)
