### ISSUE TITLE
Open Discussion: Remove PDFjs

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/app-extension-qpdfviewer#45]
I am considering to remove the PDFjs dependency and go back to just the HTML5 PDF Viewer (as it was originally). The latter is more light-weight, because it uses the internal PDF Viewer built into the browser. However, this excludes Electron/Capacitor/Cordova, etc. In which case, these platforms should use the PDFjs on their own, or an extension could be written to incorporate it.

Ever since the PDFjs dependency was added, this project has stalled out because of the issues with PDFjs.

Please voice your concerns and/or advice here.

**Comment by mesqueeb** [comment]
Maybe you can just split the library in `app-extension-qpdfviewer` and `app-extension-qpdfviewer-universal` where `universal` is the one that is capable with capacitor.

Or maybe you can split the library in `app-extension-qpdfviewer` and `app-extension-qpdfviewer-light` where `light` is the one that only has HTML5 support.

For me personally: Any place I need to show PDFs I need a solution for Capacitor as well at the same time.

**Comment by mesqueeb** [comment]
I just have a new project that will only be used in browsers, so I won't need the PDFjs dependency for that.
For some other Capacitor apps, I switched the logic to it opens PDFs inside an in-app-browser and therefor just uses the iOS browser PDF viewer. It works just as well really and it made it possible for me to remove the QPdfviewer dependency, making the app much lighter.

So I'd say: fork this repo and do one of these:
- `qpdfviewer` and `qpdfviewer-universal`
- `qpdfviewer-light` and `qpdfviewer`
- `qpdfviewer-light` and `qpdfviewer-universal`

**Comment by hawkeye64** [comment]
@mesqueeb Good point - I like the idea of `QPdfviewerLight`

**Comment by hawkeye64** [comment]
I am still on the wall for this and haven't done anything because of lack of suggestions/ideas/etc :(

**Comment by cabassi** [comment]
Hi @hawkeye64, I'm gonna report what happened when we tried to use this extension in one of our apps.

So basically we were developing an app (quasar & capacitor) for the hunters in Switzerland and we needed to show a pdf that was several pages long (>100) and it needed to work offline and refresh its contents when there was connectivity.

We ended up opening the file as an external file because this and other pdf viewers we tried were not working well on mobile because of pdfjs and it's sluggishness or because of the bad UI/UX they had.

I thinks that most use cases on capacitor, or mobile in general, are these:
1. view the pdf
1. be able to search for text in the pdf
1. see the page you are at

The top bar that is currently displayed is not very attracting on mobile 'cause it's stealing some screen real estate, which on mobile isn't many.

On mobile most of the time you just need a "pdf scroller". I'd also suggest to fork the extension and have something like this:
- qpdfviewer -> mostly to be used in desktop apps (HTML5 only)
- qpdfviewer-universal -> same as qpdfviewer, same interface, only with the support of pdfjs as a fallback when the native HTML5 viewer is not available
- qpdfviewer-mobile -> an app ext with a much simpler UI, built with pdfjs and optimized for that, and wrote with a mobile UX in mind.

I've got also some ideas on a possible UI for the qpdfviewer-mobile, let me know if you're interested in seeing a sketch!

**Comment by hawkeye64** [comment]
@cabassi Yes, please! I have recently been inspired by @jesusvilla in some recent work he has done. Hoping he will help out a bit here. Yes, I do like the multiple app-extensions. I feel pdfjs is a burden, if you just need to access the HTML 5 Pdf Viewer.

**Comment by jesusvilla** [comment]
Thank's for the interesting ideas.
To make the pdf viewer, it is necessary to have pdf.js but not its viewer, if not the core and thus achieve full control of the UI, that is why we are working on it, so everything lives within the Quasar ecosystem ( created and optimized on Quasar components) in turn taking into account the user experience on mobile devices which implies some mobile gestures, among other things, so I ask you a little more time, I have been inspired by the main libraries of the market: PDFTron and PSDPFKit.
![image](https://user-images.githubusercontent.com/16493932/92658056-873dc580-f2bb-11ea-8124-5fe1a022f6eb.png)
![image](https://user-images.githubusercontent.com/16493932/92658931-05e73280-f2bd-11ea-9972-ba349c111568.png)

**Comment by cabassi** [comment]
I agree with you @jesusvilla, the mobile ext needs to take into account for mobile UX!
And in my opinion you don't need to be able to edit the pdf, highlight text ect..

I mean, you can maybe on a tablet, but for smartphone I think less than 1% of the apps that shows a pdf need to edit it.
Of course, if editing capabilities are needed one could always use qpdfviewer-universal and go home with it.

I made a [very basic XD](https://xd.adobe.com/view/3ce053d4-2c76-4cba-a0ce-92fdbeb5af0e-69b3/)

Some additional considerations:
1. The overlay (called info overlay) that shows the page you're at and the search button appears only when you are scrolling and disappears automatically after you stay still for more than 3 seconds. This way you can read the pdf without distraction and enjoying the full content. In XD this is not well represented because of the XD's own limitations. 
1. When you scroll down the page number is updated accordingly to your viewport and the info overlay stays fixed on top of the page.
1. There's no need for a page selector since scrolling is so fast that for less than 300 pages it faster to scroll rather than opening the page selector, typing the page number and tap Go.

This behavior is very similar to how Apple Safari works when showing PDFs.

@jesusvilla a note: what are you saying about PDFtron and PSDPFkit is valuable and these are good ideas for the desktop version of this extension, but for mobile, I think it's not worth it.

What do you think ?

**Comment by hawkeye64** [comment]
@cabassi I like where you are going with the design. I am curious what would be in the hamburger menu...

**Comment by cabassi** [comment]
The hamburger menu is just for navigation. I extracted this from a mockup of the [JagdGR app](https://jagdgr.ch/)

What I wanted to show was just the super minimalist overlay which is shown when you scroll the pdf.
I find qpdfviewer-mobile should be that simple.

Do you think that's something you may be interested to develop ? What are your thoughts on mobile pdf fruition ?

**Comment by jesusvilla** [comment]
Desktop version
![unknown](https://user-images.githubusercontent.com/16493932/93492804-db0a6900-f8d0-11ea-9d2c-13030d4f59b9.png)


Mobile version 
![20200917_102923](https://user-images.githubusercontent.com/16493932/93492733-be6e3100-f8d0-11ea-8a6a-f4b61ded0d04.png)

**Comment by jesusvilla** [comment]
I think there should be a property with 3 modes: desktop, mobile, auto. By default it will be in ``auto`` determined by vm.$q.screen.lt.sm so that it is indicated in mobile mode.
The main difference will be the toolbar, with it comes mobile support and its gestures, I hope to get to pinchzoom. 

![QPdfViewer - mode(auto)](https://user-images.githubusercontent.com/16493932/93516219-5713a980-f8ef-11ea-8eb2-71ed5ace652d.gif)

I'm still developing it, so ask for a little patience please as i'm taking into account UI and performance. I hope it is to the liking of the whole community. :heart:

**Comment by cabassi** [comment]
@jesusvilla That's a fantastic news! I'm sure the community as a whole is going to appreciate your hard work.

As for the mobile, what plans do you have about navigation between pages and in the page itself?
Do you think you'll be able to implement pan to move inside the page and scroll up and down to navigate between pages?

**Comment by jesusvilla** [comment]
Thank you @cabassi, by mobile do you mean this?
![QPdfViewer - mobile](https://user-images.githubusercontent.com/16493932/93523729-16b92900-f8f9-11ea-97d5-39b699a8b648.gif)

**Comment by cabassi** [comment]
> Thank you @cabassi, by mobile do you mean this?
> ![QPdfViewer - mobile](https://user-images.githubusercontent.com/16493932/93523729-16b92900-f8f9-11ea-97d5-39b699a8b648.gif)

Yes! Sorry I didn't imply that was a thing since a saw the two arrows for navigation. In fact I wonder what are these for if you can scroll with your thumb ;)

Btw it seems pretty neat already!

**Comment by jesusvilla** [comment]
the navigation buttons have the other viewers, so I put them, it's never too much. :wink:

**Comment by cabassi** [comment]
Personally, for mobile I think they're not needed. 

I found counterproductive when you give a user too much ways to do a thing. Of course it's not the case for a thing that simple like a scroll / tap a button.

Maybe you can have a prop to hide / show the arrow buttons, so if someone feels it's not needed they can just hide them.

I'm looking forward to see this ext :)

**Comment by jesusvilla** [comment]
I agree with you, overloading with options is bad, but this is not the case, sometimes it is easier to scroll directly on each page (navigation button) or other users may believe that it's more comfortable with using the scroll. Also, the idea is that each button can be shown or hidden.

**Comment by cabassi** [comment]
You thought every detail. Thanks for your work!

Feel free to ask for feedback or help with testing. I'm glad to help if needed.

**Comment by jesusvilla** [comment]
@cabassi thanks for your ideas, you are already contributing a lot :+1:

**Comment by gmalignon** [comment]
I would like to add my own experience. I use QPdfviewer in a Quasar Android Cordova project and the only way I could get it to work is by using the pdfjs type. Actually unlike what the documentation states, the pdfjs type works fine with blobs. I have a core .net back end which sends a base64 string and the plugin displays PDFs fine with a blob. 
I couldn't get it to work at all using the html5 type, so I think 2 versions are needed.

**Comment by hawkeye64** [comment]
@gmalignon The html5 uses the internal PDF viewer built into browsers. Electron and mobiles do not have this capability. That's why PDFjs was origainally added. However, PDFjs has more flexibility that can be programatically accessed.It's likely we will now keep PDFjs and ditch the html5 version.

**Comment by hawkeye64** [comment]
The latest was just released with Quasar v2/Vue v3 support.
https://github.com/quasarframework/app-extension-qpdfviewer/releases/tag/v2.0.0-alpha.1
Closing this issue. If you feel the need create a new issue. Thanks.
