### ISSUE TITLE
Tests found that PDF files on the mobile side could not be previewed properly

### ISSUE THREAD

**Issue by jglie** [quasarframework/app-extension-qpdfviewer#67]

**Comment by hawkeye64** [comment]
@jglie One of the reasons why we'll be switching to PDFjs completely, instead of relying on the browser's native PDF viewer. Not all mobile browsers have one, not does Electron, Capacitor or Cordova. Bear with us as we are experiencing some technical difficulties in getting this sorted.
In the meantime, which OS (mobile type and versions) and what browser(s)?

**Comment by jglie** [comment]
@hawkeye64 Using the Google browser (version 86.0.4240.75), I switched to debug mode to simulate the mobile preview, but found that the browser blocked the PDF preview.
![image](https://user-images.githubusercontent.com/13246786/96822986-ef0c3200-145d-11eb-9eb6-278f3c4f2c0b.png)
But. Firefox debugging test is ok

**Comment by hawkeye64** [comment]
The latest was just released with Quasar v2/Vue v3 support.
https://github.com/quasarframework/app-extension-qpdfviewer/releases/tag/v2.0.0-alpha.1
Closing this issue. If you feel the need create a new issue. Thanks.
